sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sunicho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunicho/docker-react npm run test