sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sunicho/dockcer-react -f Dockderfile.dev .

script:
  - docker run -e CI=true sunicho/docker-react npm run test