sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sunicho/dockcer-react -f Dockderfile.dev .

script:
  - docker run sunicho/docker-react npm run test -- -- coverage